"""Compute cepstral sigma from a LAMMPS current.dat trace.

current.dat is the per-step charge-current dump written by the production
input script generated by scripts/curate_ff_md_data.py. It has 6 columns per
data line in the order:

    J_ALL(x,y,z), J_LI(x,y,z), J_ANION(x,y,z), J_NEUTRAL(x,y,z)

each in LAMMPS real units of e·Å/fs (sum of q_i · v_i over the LIGROUP or
ANIONGROUP molecules). LAMMPS's `fix ave/time 1 1 1` writes one line per
timestep, with the first column being the simulation step number.

The cepstral estimator expects a CurrentBurstSet with block_currents shape
(n_bursts, n_steps, 2, 3) where n_blocks=2 is the cation/anion split. This
script reshapes current.dat into that form and routes through the existing
estimator — same pipeline as predict_sigma.

Usage:
    python -m conductivity.fm_md.sigma_from_current_dat \\
        --current-dat <path>/current.dat \\
        --composition-json <path>/<tag>.composition.json \\
        --copies-json <path>/<tag>.copies.json \\
        --burn-ps 5.0 \\
        --dt-fs 1.0
"""

from __future__ import annotations

import control_framework.jax_m4_tuning  # noqa: F401 -- must precede any jax import

import argparse
import logging
from dataclasses import dataclass
from pathlib import Path
from statistics import NormalDist

import numpy as np

from constants import CARTESIAN_COMPONENT_COUNT, CEPSTRAL_MIN_BURST_STEPS
from foundation_model.current_spectrum_estimator import CurrentBurstSet
from foundation_model.cepstral_conductivity import (
    CepstralConductivityEstimate,
    SegmentationConfig,
    TruncationAIC,
    estimate_conductivity_cepstral,
)
from conductivity.fm_md.sigma_from_trajectory import (
    DPSS_N_TAPERS,
    DPSS_TIME_BANDWIDTH,
    N_BOOTSTRAP,
    RANDOM_SEED,
)
from utils.strict_validation import read_json_object, write_json_object
from utils.time_series_statistics import dyadic_values, select_stationary_suffix

logger = logging.getLogger(__name__)
DECIMATION_REFINEMENT_FACTOR = 2
CURRENT_BLOCK_LABELS = ("cation", "anion", "neutral")
CURRENT_TOTAL_CHANNEL_COUNT = 1


@dataclass(frozen=True)
class CurrentDatInputs:
    """Resolved inputs needed to run cepstral sigma on a LAMMPS current.dat."""

    current_dat: Path
    dt_fs: float
    temperature_K: float
    volume_ang3: float


@dataclass(frozen=True)
class AdaptiveCurrentEstimate:
    selected_estimate: CepstralConductivityEstimate
    stationary_start_step: int
    effective_sample_size: float
    selected_current_stride_steps: int
    evaluated_current_stride_steps: tuple[int, ...]
    stride_conductivities_mS_cm: tuple[float, ...]
    evaluated_burst_counts: tuple[int, ...]
    evaluated_conductivities_mS_cm: tuple[float, ...]


def _read_box_volume_from_lammps_data(data_path: Path) -> float:
    """Parse a LAMMPS data file header and return the box volume in Å^3.

    The header contains lines like
        xlo xhi  ylo yhi  zlo zhi
    each carrying two floats. For a triclinic box there is an additional
    `xy xz yz` line (we currently only support orthogonal post-eq boxes
    since change_box all ortho has run by this point).
    """
    text = data_path.read_text()
    box_edges = []
    for axis in ("xlo xhi", "ylo yhi", "zlo zhi"):
        line = next((ln for ln in text.splitlines() if ln.strip().endswith(axis)), None)
        if line is None:
            raise ValueError(f"{data_path} missing '{axis}' header line")
        parts = line.split()
        lo, hi = float(parts[0]), float(parts[1])
        box_edges.append(hi - lo)
    if "xy xz yz" in text:
        line = next(ln for ln in text.splitlines() if ln.strip().endswith("xy xz yz"))
        parts = line.split()
        xy, xz, yz = float(parts[0]), float(parts[1]), float(parts[2])
        if max(abs(xy), abs(xz), abs(yz)) > 1e-6:
            raise ValueError(
                f"{data_path} has non-zero tilt (xy={xy}, xz={xz}, yz={yz}); "
                f"sigma_from_current_dat currently only handles orthogonal boxes"
            )
    volume = box_edges[0] * box_edges[1] * box_edges[2]
    logger.info(
        "Equilibrated box from %s: %.3f × %.3f × %.3f Å = %.1f Å^3",
        data_path.name,
        box_edges[0],
        box_edges[1],
        box_edges[2],
        volume,
    )
    return volume


def _read_current_dat(path: Path) -> np.ndarray:
    """Load a LAMMPS fix ave/time current.dat file.

    Returns J(t) shape (n_steps, n_currents). LAMMPS fix ave/time writes one
    line per timestep, with column 0 the step id and columns 1..n the
    user-supplied compute values. Comment lines starting with # are skipped
    by np.loadtxt; we drop the step column afterward.
    """
    raw = np.loadtxt(path, comments="#", dtype=np.float64)
    if raw.ndim != 2:
        raise ValueError(
            f"current.dat at {path} parsed to shape {raw.shape}; expected 2D"
        )
    j_t = raw[:, 1:]  # strip step column
    logger.info(
        "Loaded %d rows × %d current columns from %s", j_t.shape[0], j_t.shape[1], path
    )
    return j_t


def sigma_from_current_dat(
    inputs: CurrentDatInputs,
    confidence_level: float,
    minimum_effective_sample_size: float,
) -> AdaptiveCurrentEstimate:
    """Estimate conductivity after automatic stationarity and burst refinement."""
    j_t = _read_current_dat(inputs.current_dat)
    if not 0.0 < confidence_level < 1.0:
        raise ValueError("confidence_level must be between zero and one")
    standard_error_limit = NormalDist().inv_cdf(0.5 + 0.5 * confidence_level)
    expected_current_component_count = int(CARTESIAN_COMPONENT_COUNT) * (
        CURRENT_TOTAL_CHANNEL_COUNT + len(CURRENT_BLOCK_LABELS)
    )
    if j_t.shape[1] != expected_current_component_count:
        raise ValueError(
            "current.dat must contain total, cation, anion, and neutral "
            "three-component currents"
        )
    total_current = j_t[:, : int(CARTESIAN_COMPONENT_COUNT)]
    stationary_suffix = select_stationary_suffix(
        values=np.linalg.norm(total_current, axis=1),
        maximum_split_mean_difference_standard_errors=standard_error_limit,
        maximum_linear_drift_standard_errors=standard_error_limit,
        minimum_effective_sample_size=minimum_effective_sample_size,
    )
    stationary_currents = j_t[stationary_suffix.start_index :]

    # Columns are [Jx_Li, Jy_Li, Jz_Li, Jx_An, Jy_An, Jz_An]. Reshape to
    # (n_steps, 2 blocks, 3 xyz). The reshape fails loudly if the column
    # count is wrong, so no explicit n_cols check is needed.
    maximum_stride = stationary_currents.shape[0] // (
        DECIMATION_REFINEMENT_FACTOR * CEPSTRAL_MIN_BURST_STEPS
    )
    if maximum_stride < 1:
        raise ValueError(
            "stationary current suffix is too short for two cepstral bursts"
        )
    current_stride_steps = dyadic_values(1, maximum_stride)
    stride_estimates = tuple(
        _stable_cepstral_estimate(
            currents=stationary_currents[::stride_steps],
            inputs=inputs,
            current_stride_steps=stride_steps,
        )
        for stride_steps in current_stride_steps
    )
    reference_estimate = stride_estimates[0][0]
    accepted_stride_indices = tuple(
        stride_index
        for stride_index, (
            candidate_estimate,
            _burst_counts,
            _conductivities,
        ) in enumerate(stride_estimates)
        if _bootstrap_intervals_overlap(reference_estimate, candidate_estimate)
    )
    selected_stride_index = accepted_stride_indices[-1]
    estimate, burst_counts, burst_conductivities = stride_estimates[
        selected_stride_index
    ]
    logger.info(
        "selected current stride %d from offline decimation candidates %s",
        current_stride_steps[selected_stride_index],
        current_stride_steps,
    )
    return AdaptiveCurrentEstimate(
        selected_estimate=estimate,
        stationary_start_step=stationary_suffix.start_index,
        effective_sample_size=(stationary_suffix.autocorrelation.effective_sample_size),
        selected_current_stride_steps=current_stride_steps[selected_stride_index],
        evaluated_current_stride_steps=current_stride_steps,
        stride_conductivities_mS_cm=tuple(
            candidate_estimate.sigma_mS_cm
            for candidate_estimate, _burst_counts, _conductivities in stride_estimates
        ),
        evaluated_burst_counts=burst_counts,
        evaluated_conductivities_mS_cm=burst_conductivities,
    )


def _stable_cepstral_estimate(
    currents: np.ndarray,
    inputs: CurrentDatInputs,
    current_stride_steps: int,
) -> tuple[CepstralConductivityEstimate, tuple[int, ...], tuple[float, ...]]:
    step_count = currents.shape[0]
    block_steps = currents[:, int(CARTESIAN_COMPONENT_COUNT) :].reshape(
        step_count,
        len(CURRENT_BLOCK_LABELS),
        int(CARTESIAN_COMPONENT_COUNT),
    )
    maximum_burst_count = step_count // CEPSTRAL_MIN_BURST_STEPS
    burst_counts = dyadic_values(DECIMATION_REFINEMENT_FACTOR, maximum_burst_count)
    estimates = tuple(
        _cepstral_estimate_for_burst_count(
            block_steps,
            inputs,
            burst_count,
            current_stride_steps,
        )
        for burst_count in burst_counts
    )
    stable_indices = tuple(
        estimate_index
        for estimate_index in range(1, len(estimates))
        if _bootstrap_intervals_overlap(
            estimates[estimate_index - 1], estimates[estimate_index]
        )
    )
    if not stable_indices:
        raise ValueError("cepstral conductivity is not stable across burst refinement")
    selected_index = stable_indices[0]
    selected_width = _bootstrap_interval_width(estimates[selected_index])
    for candidate_index in stable_indices[1:]:
        candidate_width = _bootstrap_interval_width(estimates[candidate_index])
        if candidate_width < selected_width:
            selected_index = candidate_index
            selected_width = candidate_width
    return (
        estimates[selected_index],
        burst_counts,
        tuple(candidate.sigma_mS_cm for candidate in estimates),
    )


def _log_selected_estimate(estimate: CepstralConductivityEstimate) -> None:
    logger.info(
        "σ = %.3f mS/cm  (bootstrap CI [%.3f, %.3f], asymptotic CI [%.3f, %.3f], P*=%d)",
        estimate.sigma_mS_cm,
        estimate.bootstrap_ci_low_mS_cm,
        estimate.bootstrap_ci_high_mS_cm,
        estimate.asymptotic_ci_low_mS_cm,
        estimate.asymptotic_ci_high_mS_cm,
        estimate.P_star,
    )


def _cepstral_estimate_for_burst_count(
    block_steps: np.ndarray,
    inputs: CurrentDatInputs,
    burst_count: int,
    current_stride_steps: int,
) -> CepstralConductivityEstimate:
    steps_per_burst = block_steps.shape[0] // burst_count
    retained_step_count = burst_count * steps_per_burst
    block_currents = block_steps[:retained_step_count].reshape(
        burst_count,
        steps_per_burst,
        len(CURRENT_BLOCK_LABELS),
        int(CARTESIAN_COMPONENT_COUNT),
    )
    burst_set = CurrentBurstSet(
        block_currents=block_currents,
        dt_fs=inputs.dt_fs * current_stride_steps,
        volume_ang3=inputs.volume_ang3,
        temperature_K=inputs.temperature_K,
        block_labels=list(CURRENT_BLOCK_LABELS),
    )
    return estimate_conductivity_cepstral(
        burst_set=burst_set,
        truncation=TruncationAIC(),
        segmentation=SegmentationConfig(
            segment_length=steps_per_burst,
            overlap=0,
            n_tapers=DPSS_N_TAPERS,
            time_bandwidth=DPSS_TIME_BANDWIDTH,
        ),
        n_bootstrap=N_BOOTSTRAP,
        random_seed=RANDOM_SEED,
    )


def _bootstrap_intervals_overlap(
    first: CepstralConductivityEstimate,
    second: CepstralConductivityEstimate,
) -> bool:
    return max(first.bootstrap_ci_low_mS_cm, second.bootstrap_ci_low_mS_cm) <= min(
        first.bootstrap_ci_high_mS_cm, second.bootstrap_ci_high_mS_cm
    )


def _bootstrap_interval_width(estimate: CepstralConductivityEstimate) -> float:
    return estimate.bootstrap_ci_high_mS_cm - estimate.bootstrap_ci_low_mS_cm


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(message)s")
    ap = argparse.ArgumentParser(description="Cepstral sigma from LAMMPS current.dat")
    ap.add_argument("--current-dat", required=True, type=Path)
    ap.add_argument(
        "--composition-json",
        required=True,
        type=Path,
        help="Composition JSON written by curate_ff_md_data.py (gives T_K)",
    )
    ap.add_argument(
        "--eq-data-lmp",
        required=True,
        type=Path,
        help="LAMMPS .eq.lmp data file written after NPT equilibration. The "
        "box volume is read from its header (post-NPT volume, not the "
        "initial packmol target).",
    )
    ap.add_argument("--confidence-level", type=float, required=True)
    ap.add_argument("--minimum-effective-sample-size", type=float, required=True)
    ap.add_argument(
        "--dt-fs",
        type=float,
        required=True,
        help="LAMMPS timestep in fs (must match what was used by the MD run)",
    )
    ap.add_argument("--output-json", type=Path, required=True)
    args = ap.parse_args()

    spec = read_json_object(args.composition_json, "MD composition")
    inputs = CurrentDatInputs(
        current_dat=args.current_dat,
        dt_fs=args.dt_fs,
        temperature_K=float(spec["temperature_K"]),
        volume_ang3=_read_box_volume_from_lammps_data(args.eq_data_lmp),
    )
    logger.info(
        "Inputs: T=%.1f K, V=%.1f Å^3, dt=%.2f fs",
        inputs.temperature_K,
        inputs.volume_ang3,
        inputs.dt_fs,
    )

    adaptive_estimate = sigma_from_current_dat(
        inputs=inputs,
        confidence_level=args.confidence_level,
        minimum_effective_sample_size=args.minimum_effective_sample_size,
    )
    estimate = adaptive_estimate.selected_estimate
    _log_selected_estimate(estimate)
    print(
        f"σ = {estimate.sigma_mS_cm:.3f} mS/cm  "
        f"(bootstrap CI [{estimate.bootstrap_ci_low_mS_cm:.3f}, {estimate.bootstrap_ci_high_mS_cm:.3f}], "
        f"P*={estimate.P_star})"
    )
    write_json_object(
        args.output_json,
        {
            "sigma_mS_cm": estimate.sigma_mS_cm,
            "bootstrap_ci_low_mS_cm": estimate.bootstrap_ci_low_mS_cm,
            "bootstrap_ci_high_mS_cm": estimate.bootstrap_ci_high_mS_cm,
            "asymptotic_ci_low_mS_cm": estimate.asymptotic_ci_low_mS_cm,
            "asymptotic_ci_high_mS_cm": estimate.asymptotic_ci_high_mS_cm,
            "P_star": estimate.P_star,
            "stationary_start_step": adaptive_estimate.stationary_start_step,
            "effective_sample_size": adaptive_estimate.effective_sample_size,
            "selected_current_stride_steps": (
                adaptive_estimate.selected_current_stride_steps
            ),
            "evaluated_current_stride_steps": (
                adaptive_estimate.evaluated_current_stride_steps
            ),
            "stride_conductivities_mS_cm": (
                adaptive_estimate.stride_conductivities_mS_cm
            ),
            "evaluated_burst_counts": adaptive_estimate.evaluated_burst_counts,
            "evaluated_conductivities_mS_cm": (
                adaptive_estimate.evaluated_conductivities_mS_cm
            ),
        },
        "Green-Kubo current estimate",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
