"""Compute cepstral sigma from a LAMMPS current.dat trace.

current.dat is the per-step charge-current dump written by the production
input script generated by scripts/curate_ff_md_data.py. It has 6 columns per
data line in the order:

    c_JX_LI c_JY_LI c_JZ_LI c_JX_AN c_JY_AN c_JZ_AN

each in LAMMPS real units of e·Å/fs (sum of q_i · v_i over the LIGROUP or
ANIONGROUP molecules). LAMMPS's `fix ave/time 1 1 1` writes one line per
timestep, with the first column being the simulation step number.

The cepstral estimator expects a CurrentBurstSet with block_currents shape
(n_bursts, n_steps, 2, 3) where n_blocks=2 is the cation/anion split. This
script reshapes current.dat into that form and routes through the existing
estimator — same pipeline as predict_sigma.

Usage:
    python -m conductivity.fm_md.sigma_from_current_dat \\
        --current-dat <path>/current.dat \\
        --composition-json <path>/<tag>.composition.json \\
        --copies-json <path>/<tag>.copies.json \\
        --burn-ps 5.0 \\
        --dt-fs 1.0
"""

from __future__ import annotations

import control_framework.jax_m4_tuning  # noqa: F401 -- must precede any jax import

import argparse
import json
import logging
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from constants import CEPSTRAL_MIN_BURST_STEPS
from foundation_model.current_spectrum_estimator import CurrentBurstSet
from foundation_model.cepstral_conductivity import (
    CepstralConductivityEstimate,
    SegmentationConfig,
    TruncationAIC,
    estimate_conductivity_cepstral,
)
from conductivity.fm_md.sigma_from_trajectory import (
    DPSS_N_TAPERS,
    DPSS_TIME_BANDWIDTH,
    N_BOOTSTRAP,
    N_BURSTS_DEFAULT,
    RANDOM_SEED,
)

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class CurrentDatInputs:
    """Resolved inputs needed to run cepstral sigma on a LAMMPS current.dat."""
    current_dat: Path
    burn_ps: float
    dt_fs: float
    temperature_K: float
    volume_ang3: float


def _read_box_volume_from_lammps_data(data_path: Path) -> float:
    """Parse a LAMMPS data file header and return the box volume in Å^3.

    The header contains lines like
        xlo xhi  ylo yhi  zlo zhi
    each carrying two floats. For a triclinic box there is an additional
    `xy xz yz` line (we currently only support orthogonal post-eq boxes
    since change_box all ortho has run by this point).
    """
    text = data_path.read_text()
    box_edges = []
    for axis in ("xlo xhi", "ylo yhi", "zlo zhi"):
        line = next((ln for ln in text.splitlines() if ln.strip().endswith(axis)), None)
        if line is None:
            raise ValueError(f"{data_path} missing '{axis}' header line")
        parts = line.split()
        lo, hi = float(parts[0]), float(parts[1])
        box_edges.append(hi - lo)
    if "xy xz yz" in text:
        line = next(ln for ln in text.splitlines() if ln.strip().endswith("xy xz yz"))
        parts = line.split()
        xy, xz, yz = float(parts[0]), float(parts[1]), float(parts[2])
        if max(abs(xy), abs(xz), abs(yz)) > 1e-6:
            raise ValueError(
                f"{data_path} has non-zero tilt (xy={xy}, xz={xz}, yz={yz}); "
                f"sigma_from_current_dat currently only handles orthogonal boxes"
            )
    volume = box_edges[0] * box_edges[1] * box_edges[2]
    logger.info("Equilibrated box from %s: %.3f × %.3f × %.3f Å = %.1f Å^3",
                data_path.name, box_edges[0], box_edges[1], box_edges[2], volume)
    return volume


def _read_current_dat(path: Path) -> np.ndarray:
    """Load a LAMMPS fix ave/time current.dat file.

    Returns J(t) shape (n_steps, n_currents). LAMMPS fix ave/time writes one
    line per timestep, with column 0 the step id and columns 1..n the
    user-supplied compute values. Comment lines starting with # are skipped
    by np.loadtxt; we drop the step column afterward.
    """
    raw = np.loadtxt(path, comments="#", dtype=np.float64)
    if raw.ndim != 2:
        raise ValueError(f"current.dat at {path} parsed to shape {raw.shape}; expected 2D")
    j_t = raw[:, 1:]  # strip step column
    logger.info("Loaded %d rows × %d current columns from %s",
                j_t.shape[0], j_t.shape[1], path)
    return j_t


def sigma_from_current_dat(inputs: CurrentDatInputs) -> CepstralConductivityEstimate:
    """Run the project's cepstral conductivity estimator on a LAMMPS current.dat.

    Drops the first inputs.burn_ps picoseconds of the trace as burn-in
    (the Langevin thermostat coupling transient after NPT->NVE switch),
    then splits the remaining J(t) into N_BURSTS_DEFAULT bursts and routes
    through estimate_conductivity_cepstral.
    """
    j_t = _read_current_dat(inputs.current_dat)
    n_total = j_t.shape[0]

    n_burn = int(round(inputs.burn_ps * 1000.0 / inputs.dt_fs))
    if n_burn >= n_total:
        raise ValueError(
            f"burn_ps={inputs.burn_ps} ({n_burn} steps) >= total steps {n_total}"
        )
    j_t = j_t[n_burn:]
    logger.info("Dropped %d burn-in steps; %d steps remain (%.1f ps)",
                n_burn, j_t.shape[0], j_t.shape[0] * inputs.dt_fs / 1000.0)

    # Columns are [Jx_Li, Jy_Li, Jz_Li, Jx_An, Jy_An, Jz_An]. Reshape to
    # (n_steps, 2 blocks, 3 xyz). The reshape fails loudly if the column
    # count is wrong, so no explicit n_cols check is needed.
    n_steps = j_t.shape[0]
    block_steps = j_t.reshape(n_steps, 2, 3)

    n_bursts = N_BURSTS_DEFAULT
    n_per_burst = n_steps // n_bursts
    if n_per_burst < CEPSTRAL_MIN_BURST_STEPS:
        raise ValueError(
            f"Each burst would have {n_per_burst} steps (need "
            f">= {CEPSTRAL_MIN_BURST_STEPS} for cepstral). "
            f"Need a longer production run or fewer bursts."
        )
    n_keep = n_bursts * n_per_burst
    block_currents = block_steps[:n_keep].reshape(n_bursts, n_per_burst, 2, 3)
    logger.info(
        "Block currents shape %s (n_bursts=%d, n_per_burst=%d, %.1f ps/burst)",
        block_currents.shape, n_bursts, n_per_burst,
        n_per_burst * inputs.dt_fs / 1000.0,
    )

    burst_set = CurrentBurstSet(
        block_currents=block_currents,
        dt_fs=inputs.dt_fs,
        volume_ang3=inputs.volume_ang3,
        temperature_K=inputs.temperature_K,
        block_labels=["cation", "anion"],
    )
    segmentation = SegmentationConfig(
        segment_length=n_per_burst,
        overlap=0,
        n_tapers=DPSS_N_TAPERS,
        time_bandwidth=DPSS_TIME_BANDWIDTH,
    )
    estimate = estimate_conductivity_cepstral(
        burst_set=burst_set,
        truncation=TruncationAIC(),
        segmentation=segmentation,
        n_bootstrap=N_BOOTSTRAP,
        random_seed=RANDOM_SEED,
    )
    logger.info(
        "σ = %.3f mS/cm  (bootstrap CI [%.3f, %.3f], asymptotic CI [%.3f, %.3f], P*=%d)",
        estimate.sigma_mS_cm,
        estimate.bootstrap_ci_low_mS_cm, estimate.bootstrap_ci_high_mS_cm,
        estimate.asymptotic_ci_low_mS_cm, estimate.asymptotic_ci_high_mS_cm,
        estimate.P_star,
    )
    return estimate


def main() -> int:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s | %(message)s")
    ap = argparse.ArgumentParser(description="Cepstral sigma from LAMMPS current.dat")
    ap.add_argument("--current-dat", required=True, type=Path)
    ap.add_argument("--composition-json", required=True, type=Path,
                    help="Composition JSON written by curate_ff_md_data.py (gives T_K)")
    ap.add_argument("--eq-data-lmp", required=True, type=Path,
                    help="LAMMPS .eq.lmp data file written after NPT equilibration. The "
                         "box volume is read from its header (post-NPT volume, not the "
                         "initial packmol target).")
    ap.add_argument("--burn-ps", type=float, required=True,
                    help="Burn-in (ps) to drop from start of current.dat (Langevin coupling transient)")
    ap.add_argument("--dt-fs", type=float, required=True,
                    help="LAMMPS timestep in fs (must match what was used by the MD run)")
    args = ap.parse_args()

    spec = json.loads(args.composition_json.read_text())
    inputs = CurrentDatInputs(
        current_dat=args.current_dat,
        burn_ps=args.burn_ps,
        dt_fs=args.dt_fs,
        temperature_K=float(spec["temperature_K"]),
        volume_ang3=_read_box_volume_from_lammps_data(args.eq_data_lmp),
    )
    logger.info("Inputs: T=%.1f K, V=%.1f Å^3, dt=%.2f fs, burn=%.1f ps",
                inputs.temperature_K, inputs.volume_ang3, inputs.dt_fs, inputs.burn_ps)

    estimate = sigma_from_current_dat(inputs)
    print(f"σ = {estimate.sigma_mS_cm:.3f} mS/cm  "
          f"(bootstrap CI [{estimate.bootstrap_ci_low_mS_cm:.3f}, {estimate.bootstrap_ci_high_mS_cm:.3f}], "
          f"P*={estimate.P_star})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
